coverage:
  status:
    project:
      default:
        target: auto
        # Codecov should allow coverage to be reduced by a few percent
        threshold: 2%
    patch:
      default:
        informational: true
