services:
  hyperion-db:
    image: postgres:15.1-alpine3.17
    container_name: hyperion-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGTZ: ${POSTGRES_TZ}
    ports:
      - 5432:5432
    volumes:
      - ./hyperion-db:/var/lib/postgresql/data

  hyperion-redis:
    image: redis:7.0-alpine3.17
    container_name: hyperion-redis-dev
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./hyperion-redis:/data

volumes:
  hyperion_db_data:
