FROM ghcr.io/astral-sh/uv:python3.11-bookworm

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV UV_COMPILE_BYTECODE=1

WORKDIR /hyperion

COPY requirements-common.txt .
RUN uv pip install --system --no-cache-dir -r requirements-common.txt

ENTRYPOINT ["/bin/bash"]