"""10-ph

Create Date: 2024-05-08 13:02:15.712830
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.types.sqlalchemy import TZDateTime

# revision identifiers, used by Alembic.
revision: str = "fce1716123e2"
down_revision: str | None = "7b2d2f884627"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ph_papers",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("release_date", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ph_papers_id"), "ph_papers", ["id"], unique=False)
    op.create_table(
        "phonebook_association",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "comity",
                "section_ae",
                "club_ae",
                "section_use",
                "club_use",
                "association_independant",
                name="kinds",
            ),
            nullable=False,
        ),
        sa.Column("mandate_year", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_phonebook_association_id"),
        "phonebook_association",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_phonebook_association_name"),
        "phonebook_association",
        ["name"],
        unique=False,
    )
    op.create_table(
        "recommendation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("creation", TZDateTime(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=True),
        sa.Column("summary", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "phonebook_membership",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("association_id", sa.String(), nullable=False),
        sa.Column("mandate_year", sa.Integer(), nullable=False),
        sa.Column("role_name", sa.String(), nullable=False),
        sa.Column("role_tags", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["association_id"], ["phonebook_association.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["core_user.id"]),
        sa.PrimaryKeyConstraint("user_id", "association_id", "mandate_year"),
    )
    op.create_index(
        op.f("ix_phonebook_membership_id"),
        "phonebook_membership",
        ["id"],
        unique=False,
    )
    op.add_column("loan", sa.Column("returned_date", sa.Date(), nullable=True))
    op.alter_column(
        "loaner_item",
        "suggested_lending_duration",
        existing_type=sa.DATETIME(),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.alter_column(
        "notification_message",
        "expire_on",
        existing_type=sa.DATE(),
        type_=TZDateTime(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "notification_message",
        "expire_on",
        existing_type=TZDateTime(),
        type_=sa.DATE(),
        existing_nullable=False,
    )
    op.alter_column(
        "loaner_item",
        "suggested_lending_duration",
        existing_type=sa.Integer(),
        type_=sa.DATETIME(),
        existing_nullable=False,
    )
    op.drop_column("loan", "returned_date")
    op.drop_index(op.f("ix_phonebook_membership_id"), table_name="phonebook_membership")
    op.drop_table("phonebook_membership")
    op.drop_table("recommendation")
    op.drop_index(
        op.f("ix_phonebook_association_name"),
        table_name="phonebook_association",
    )
    op.drop_index(
        op.f("ix_phonebook_association_id"),
        table_name="phonebook_association",
    )
    op.drop_table("phonebook_association")
    op.drop_index(op.f("ix_ph_papers_id"), table_name="ph_papers")
    op.drop_table("ph_papers")
    # ### end Alembic commands ###
