"""empty message

Create Date: 2024-05-02 13:12:22.450383
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.types.sqlalchemy import TZDateTime

# revision identifiers, used by Alembic.
revision: str = "ec5d90c1a3c2"
down_revision: str | None = "0534d0f07976"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("raid_document") as batch_op:
        batch_op.add_column(
            column=sa.Column(
                "validation",
                sa.Enum(
                    "pending",
                    "accepted",
                    "refused",
                    "temporary",
                    name="documentvalidation",
                ),
                nullable=False,
                server_default="pending",
            ),
        )
    op.drop_column("raid_document", "validated")
    with op.batch_alter_table("raid_participant") as batch_op:
        batch_op.add_column(
            column=sa.Column("parent_authorization_id", sa.String(), nullable=True),
        )
    op.create_foreign_key(
        None, "raid_participant", "raid_document", ["parent_authorization_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("raid_document", sa.Column("validated", sa.BOOLEAN(), nullable=False))
    op.drop_column("raid_document", "validation")
    op.drop_constraint(None, "raid_participant", type_="foreignkey")
    op.drop_column("raid_participant", "parent_authorization_id")
    # ### end Alembic commands ###
