"""empty message

Create Date: 2024-05-02 13:41:27.575853
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.types.sqlalchemy import TZDateTime

# revision identifiers, used by Alembic.
revision: str = "39c3d3f06ecd"
down_revision: str | None = "ec5d90c1a3c2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("raid_document") as batch_op:
        batch_op.alter_column(
            column_name="type",
            existing_type=sa.VARCHAR(length=18),
            type_=sa.Enum(
                "id_card",
                "medical_certificate",
                "student_card",
                "raid_rules",
                "parent_authorization",
                name="documenttype",
            ),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("raid_document") as batch_op:
        batch_op.alter_column(
            column_name="type",
            existing_type=sa.Enum(
                "id_card",
                "medical_certificate",
                "student_card",
                "raid_rules",
                "parent_authorization",
                name="documenttype",
            ),
            type_=sa.VARCHAR(length=18),
            existing_nullable=False,
        )
    # ### end Alembic commands ###
