"""empty message

Create Date: 2024-05-02 13:12:22.450383
"""

from collections.abc import Sequence
from enum import Enum

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec5d90c1a3c2"
down_revision: str | None = "0534d0f07976"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


class DocumentValidation(Enum):
    pending = "pending"
    accepted = "accepted"
    refused = "refused"
    temporary = "temporary"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(DocumentValidation, name="documentvalidation").create(op.get_bind())
    op.add_column(
        "raid_document",
        column=sa.Column(
            "validation",
            sa.Enum(DocumentValidation),
            nullable=False,
            default=DocumentValidation.pending.value,
            server_default=DocumentValidation.pending.value,
        ),
    )
    op.drop_column("raid_document", "validated")
    op.add_column(
        "raid_participant",
        column=sa.Column("parent_authorization_id", sa.String(), nullable=True),
    )
    with op.batch_alter_table("raid_document") as batch_op:
        batch_op.alter_column(
            column_name="type",
            existing_type=sa.VARCHAR(length=20),
            type_=sa.Enum(
                "idCard",
                "medicalCertificate",
                "studentCard",
                "raidRules",
                "parentAuthorization",
                name="documenttype",
            ),
            existing_nullable=False,
        )
    op.add_column(
        "raid_participant",
        sa.Column(
            "is_minor",
            sa.Boolean(),
            nullable=False,
            server_default=sa.sql.false(),
        ),
    )
    op.create_foreign_key(
        None,
        "raid_participant",
        "raid_document",
        ["parent_authorization_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("raid_document", sa.Column("validated", sa.BOOLEAN(), nullable=False))
    op.drop_column("raid_document", "validation")
    op.drop_constraint(None, "raid_participant", type_="foreignkey")
    op.drop_column("raid_participant", "parent_authorization_id")
    op.drop_column("raid_participant", "is_minor")
    op.alter_column(
        "raid_document",
        "type",
        existing_type=sa.Enum(
            "idCard",
            "medicalCertificate",
            "studentCard",
            "raidRules",
            "parentAuthorization",
            name="documenttype",
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
