"""empty message

Create Date: 2025-05-29 17:32:45.619972
"""

from collections.abc import Sequence
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pytest_alembic import MigrationContext

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ea26eebe3f8d"
down_revision: str | None = "e16b58cc6084"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "myeclpay_refund", ["transaction_id"])
    op.create_unique_constraint(None, "myeclpay_request", ["transaction_id"])
    op.create_unique_constraint(
        None,
        "myeclpay_structure_manager_transfer",
        ["confirmation_token"],
    )
    op.create_unique_constraint(None, "myeclpay_wallet_device", ["ed25519_public_key"])
    # ### end Alembic commands ###


def downgrade() -> None:
    pass


def pre_test_upgrade(
    alembic_runner: "MigrationContext",
    alembic_connection: sa.Connection,
) -> None:
    pass


def test_upgrade(
    alembic_runner: "MigrationContext",
    alembic_connection: sa.Connection,
) -> None:
    pass
