"""elocaps

Revision ID: 21241f2aac83
Revises: 28aa5ef44bf3
Create Date: 2024-02-22 12:53:58.558259

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "21241f2aac83"
down_revision: str | None = "f17e6182b0a9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "elocaps_game",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column(
            "mode",
            sa.Enum("SINGLE", "CD", "CAPACKS", "SEMI_CAPACKS", name="capsmode"),
            nullable=False,
        ),
        sa.Column("is_cancelled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "elocaps_player",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column(
            "mode",
            sa.Enum("SINGLE", "CD", "CAPACKS", "SEMI_CAPACKS", name="capsmode"),
            nullable=False,
        ),
        sa.Column("elo", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["core_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "elocaps_game_player",
        sa.Column("game_id", sa.String(), nullable=False),
        sa.Column("player_id", sa.String(), nullable=False),
        sa.Column("team", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("has_confirmed", sa.Boolean(), nullable=False),
        sa.Column("elo_gain", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["elocaps_game.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["elocaps_player.id"],
        ),
        sa.PrimaryKeyConstraint("game_id", "player_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("elocaps_game_player")
    op.drop_table("elocaps_player")
    op.drop_table("elocaps_game")
    # ### end Alembic commands ###
