"""add migration file for recommendation module

Revision ID: 3f9843f165e9
Revises: 99a2c70e4a24
Create Date: 2024-03-16 06:02:34.664485

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f9843f165e9"
down_revision: str | None = "99a2c70e4a24"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recommendation",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("creation", sa.DateTime(timezone=False), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=True),
        sa.Column("summary", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recommendation")
    # ### end Alembic commands ###
