"""empty message

Create Date: 2025-09-25 13:10:51.977068
"""

from collections.abc import Sequence
from datetime import datetime
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pytest_alembic import MigrationContext

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5351256b1bfc"
down_revision: str | None = "b72df3765853"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "amap_cash", sa.Column("last_ordering_date", TZDateTime(), nullable=True)
    )
    default_time = datetime(2025, 1, 1)
    op.execute("UPDATE amap_cash SET last_ordering_date = (?)", (default_time,))
    op.alter_column("amap_cash", "last_ordering_date", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("amap_cash", "last_ordering_date")


def pre_test_upgrade(
    alembic_runner: "MigrationContext",
    alembic_connection: sa.Connection,
) -> None:
    pass


def test_upgrade(
    alembic_runner: "MigrationContext",
    alembic_connection: sa.Connection,
) -> None:
    pass
