"""MyECLPay to MyPayment

Create Date: 2025-11-29 22:50:53.781596
"""

from collections.abc import Sequence
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pytest_alembic import MigrationContext

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.types.sqlalchemy import TZDateTime

# revision identifiers, used by Alembic.
revision: str = "467ad07734c0"
down_revision: str | None = "91fadc90f892"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mypayment_used_qrcode",
        sa.Column("qr_code_id", sa.Uuid(), nullable=False),
        sa.Column("qr_code_tot", sa.Integer(), nullable=True),
        sa.Column("qr_code_iat", TZDateTime(), nullable=True),
        sa.Column("qr_code_key", sa.Uuid(), nullable=True),
        sa.Column("qr_code_store", sa.Boolean(), nullable=True),
        sa.Column("signature", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("qr_code_id"),
    )
    op.create_table(
        "mypayment_wallet",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.Enum("USER", "STORE", name="wallettype"), nullable=False),
        sa.Column("balance", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mypayment_wallet_device",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("wallet_id", sa.Uuid(), nullable=False),
        sa.Column("ed25519_public_key", sa.LargeBinary(), nullable=False),
        sa.Column("creation", TZDateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("INACTIVE", "ACTIVE", "REVOKED", name="walletdevicestatus"),
            nullable=False,
        ),
        sa.Column("activation_token", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["wallet_id"], ["mypayment_wallet.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("activation_token"),
        sa.UniqueConstraint("ed25519_public_key"),
    )
    op.create_table(
        "mypayment_withdrawal",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("wallet_id", sa.Uuid(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("creation", TZDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["wallet_id"], ["mypayment_wallet.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mypayment_structure",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("short_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("siege_address_street", sa.String(), nullable=False),
        sa.Column("siege_address_city", sa.String(), nullable=False),
        sa.Column("siege_address_zipcode", sa.String(), nullable=False),
        sa.Column("siege_address_country", sa.String(), nullable=False),
        sa.Column("siret", sa.String(), nullable=True),
        sa.Column("iban", sa.String(), nullable=False),
        sa.Column("bic", sa.String(), nullable=False),
        sa.Column("manager_user_id", sa.String(), nullable=False),
        sa.Column("creation", TZDateTime(), nullable=False),
        sa.Column("association_membership_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["association_membership_id"], ["core_association_membership.id"],
        ),
        sa.ForeignKeyConstraint(["manager_user_id"], ["core_user.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("short_id"),
    )
    op.create_table(
        "mypayment_transaction",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("debited_wallet_id", sa.Uuid(), nullable=False),
        sa.Column("debited_wallet_device_id", sa.Uuid(), nullable=False),
        sa.Column("credited_wallet_id", sa.Uuid(), nullable=False),
        sa.Column(
            "transaction_type",
            sa.Enum("DIRECT", "REQUEST", "REFUND", name="transactiontype"),
            nullable=False,
        ),
        sa.Column("seller_user_id", sa.String(), nullable=True),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("creation", TZDateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "CONFIRMED", "CANCELED", "REFUNDED", "PENDING", name="transactionstatus",
            ),
            nullable=False,
        ),
        sa.Column("store_note", sa.String(), nullable=True),
        sa.Column("qr_code_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["credited_wallet_id"], ["mypayment_wallet.id"]),
        sa.ForeignKeyConstraint(
            ["debited_wallet_device_id"], ["mypayment_wallet_device.id"],
        ),
        sa.ForeignKeyConstraint(["debited_wallet_id"], ["mypayment_wallet.id"]),
        sa.ForeignKeyConstraint(["qr_code_id"], ["mypayment_used_qrcode.qr_code_id"]),
        sa.ForeignKeyConstraint(["seller_user_id"], ["core_user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mypayment_transfer",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.Enum("HELLO_ASSO", name="transfertype"), nullable=False),
        sa.Column("transfer_identifier", sa.String(), nullable=False),
        sa.Column("approver_user_id", sa.String(), nullable=True),
        sa.Column("wallet_id", sa.Uuid(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("creation", TZDateTime(), nullable=False),
        sa.Column("confirmed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["approver_user_id"], ["core_user.id"]),
        sa.ForeignKeyConstraint(["wallet_id"], ["mypayment_wallet.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mypayment_user_payment",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("wallet_id", sa.Uuid(), nullable=False),
        sa.Column("accepted_tos_signature", TZDateTime(), nullable=False),
        sa.Column("accepted_tos_version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["core_user.id"]),
        sa.ForeignKeyConstraint(["wallet_id"], ["mypayment_wallet.id"]),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("wallet_id"),
    )
    op.create_table(
        "mypayment_invoice",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("reference", sa.String(), nullable=False),
        sa.Column("creation", TZDateTime(), nullable=False),
        sa.Column("start_date", TZDateTime(), nullable=False),
        sa.Column("end_date", TZDateTime(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("structure_id", sa.Uuid(), nullable=False),
        sa.Column("paid", sa.Boolean(), nullable=False),
        sa.Column("received", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["structure_id"], ["mypayment_structure.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reference"),
    )
    op.create_table(
        "mypayment_refund",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("transaction_id", sa.Uuid(), nullable=False),
        sa.Column("debited_wallet_id", sa.Uuid(), nullable=False),
        sa.Column("credited_wallet_id", sa.Uuid(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("creation", TZDateTime(), nullable=False),
        sa.Column("seller_user_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["credited_wallet_id"], ["mypayment_wallet.id"]),
        sa.ForeignKeyConstraint(["debited_wallet_id"], ["mypayment_wallet.id"]),
        sa.ForeignKeyConstraint(["seller_user_id"], ["core_user.id"]),
        sa.ForeignKeyConstraint(["transaction_id"], ["mypayment_transaction.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("transaction_id"),
    )
    op.create_table(
        "mypayment_store",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("structure_id", sa.Uuid(), nullable=False),
        sa.Column("wallet_id", sa.Uuid(), nullable=False),
        sa.Column("creation", TZDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["structure_id"], ["mypayment_structure.id"]),
        sa.ForeignKeyConstraint(["wallet_id"], ["mypayment_wallet.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("wallet_id"),
    )
    op.create_table(
        "mypayment_structure_manager_transfer",
        sa.Column("structure_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("confirmation_token", sa.String(), nullable=False),
        sa.Column("valid_until", TZDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["structure_id"], ["mypayment_structure.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["core_user.id"]),
        sa.PrimaryKeyConstraint("structure_id"),
        sa.UniqueConstraint("confirmation_token"),
    )
    op.create_table(
        "mypayment_invoice_detail",
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["invoice_id"], ["mypayment_invoice.id"]),
        sa.ForeignKeyConstraint(["store_id"], ["mypayment_store.id"]),
        sa.PrimaryKeyConstraint("invoice_id", "store_id"),
    )
    op.create_table(
        "mypayment_request",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("wallet_id", sa.Uuid(), nullable=False),
        sa.Column("creation", TZDateTime(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("store_note", sa.String(), nullable=True),
        sa.Column("callback", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PROPOSED", "ACCEPTED", "REFUSED", name="requeststatus"),
            nullable=False,
        ),
        sa.Column("transaction_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["store_id"], ["mypayment_store.id"]),
        sa.ForeignKeyConstraint(["transaction_id"], ["mypayment_transaction.id"]),
        sa.ForeignKeyConstraint(["wallet_id"], ["mypayment_wallet.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("transaction_id"),
    )
    op.create_table(
        "mypayment_seller",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.Column("can_bank", sa.Boolean(), nullable=False),
        sa.Column("can_see_history", sa.Boolean(), nullable=False),
        sa.Column("can_cancel", sa.Boolean(), nullable=False),
        sa.Column("can_manage_sellers", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["store_id"], ["mypayment_store.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["core_user.id"]),
        sa.PrimaryKeyConstraint("user_id", "store_id"),
    )
    op.drop_table("myeclpay_transaction")
    op.drop_table("myeclpay_structure")
    op.drop_table("myeclpay_used_qrcode")
    op.drop_table("myeclpay_structure_manager_transfer")
    op.drop_table("myeclpay_withdrawal")
    op.drop_table("myeclpay_user_payment")
    op.drop_table("myeclpay_seller")
    op.drop_table("myeclpay_invoice_detail")
    op.drop_table("myeclpay_transfer")
    op.drop_table("myeclpay_invoice")
    op.drop_table("myeclpay_wallet")
    op.drop_table("myeclpay_wallet_device")
    op.drop_table("myeclpay_refund")
    op.drop_table("myeclpay_store")
    op.drop_table("myeclpay_request")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "myeclpay_request",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("wallet_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "creation", postgresql.TIMESTAMP(), autoincrement=False, nullable=False,
        ),
        sa.Column("total", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("store_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("store_note", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("callback", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("PROPOSED", "ACCEPTED", "REFUSED", name="requeststatus"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("transaction_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["store_id"], ["myeclpay_store.id"], name="myeclpay_request_store_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["myeclpay_transaction.id"],
            name="myeclpay_request_transaction_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["myeclpay_wallet.id"],
            name="myeclpay_request_wallet_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="myeclpay_request_pkey"),
        sa.UniqueConstraint(
            "transaction_id", name="myeclpay_request_transaction_id_key",
        ),
    )
    op.create_table(
        "myeclpay_store",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("structure_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("wallet_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "creation", postgresql.TIMESTAMP(), autoincrement=False, nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["structure_id"],
            ["myeclpay_structure.id"],
            name="myeclpay_store_structure_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"], ["myeclpay_wallet.id"], name="myeclpay_store_wallet_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="myeclpay_store_pkey"),
        sa.UniqueConstraint("name", name="myeclpay_store_name_key"),
        sa.UniqueConstraint("wallet_id", name="myeclpay_store_wallet_id_key"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "myeclpay_refund",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("transaction_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("debited_wallet_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("credited_wallet_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("total", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "creation", postgresql.TIMESTAMP(), autoincrement=False, nullable=False,
        ),
        sa.Column("seller_user_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["credited_wallet_id"],
            ["myeclpay_wallet.id"],
            name="myeclpay_refund_credited_wallet_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["debited_wallet_id"],
            ["myeclpay_wallet.id"],
            name="myeclpay_refund_debited_wallet_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["seller_user_id"],
            ["core_user.id"],
            name="myeclpay_refund_seller_user_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["myeclpay_transaction.id"],
            name="myeclpay_refund_transaction_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="myeclpay_refund_pkey"),
        sa.UniqueConstraint(
            "transaction_id", name="myeclpay_refund_transaction_id_key",
        ),
    )
    op.create_table(
        "myeclpay_wallet_device",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("wallet_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "ed25519_public_key",
            postgresql.BYTEA(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "creation", postgresql.TIMESTAMP(), autoincrement=False, nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM("INACTIVE", "ACTIVE", "REVOKED", name="walletdevicestatus"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "activation_token", sa.VARCHAR(), autoincrement=False, nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["myeclpay_wallet.id"],
            name="myeclpay_wallet_device_wallet_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="myeclpay_wallet_device_pkey"),
        sa.UniqueConstraint(
            "activation_token", name="myeclpay_wallet_device_activation_token_key",
        ),
        sa.UniqueConstraint(
            "ed25519_public_key", name="myeclpay_wallet_device_ed25519_public_key_key",
        ),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "myeclpay_wallet",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM("USER", "STORE", name="wallettype"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("balance", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="myeclpay_wallet_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "myeclpay_invoice",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("reference", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "creation", postgresql.TIMESTAMP(), autoincrement=False, nullable=False,
        ),
        sa.Column(
            "start_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False,
        ),
        sa.Column(
            "end_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False,
        ),
        sa.Column("total", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("structure_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("paid", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("received", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["structure_id"],
            ["myeclpay_structure.id"],
            name="myeclpay_invoice_structure_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="myeclpay_invoice_pkey"),
        sa.UniqueConstraint("reference", name="myeclpay_invoice_reference_key"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "myeclpay_transfer",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM("HELLO_ASSO", name="transfertype"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "transfer_identifier", sa.VARCHAR(), autoincrement=False, nullable=False,
        ),
        sa.Column("approver_user_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("wallet_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("total", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "creation", postgresql.TIMESTAMP(), autoincrement=False, nullable=False,
        ),
        sa.Column("confirmed", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["approver_user_id"],
            ["core_user.id"],
            name="myeclpay_transfer_approver_user_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["myeclpay_wallet.id"],
            name="myeclpay_transfer_wallet_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="myeclpay_transfer_pkey"),
    )
    op.create_table(
        "myeclpay_invoice_detail",
        sa.Column("invoice_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("store_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("total", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["myeclpay_invoice.id"],
            name="myeclpay_invoice_detail_invoice_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["myeclpay_store.id"],
            name="myeclpay_invoice_detail_store_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "invoice_id", "store_id", name="myeclpay_invoice_detail_pkey",
        ),
    )
    op.create_table(
        "myeclpay_seller",
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("store_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("can_bank", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("can_see_history", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("can_cancel", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "can_manage_sellers", sa.BOOLEAN(), autoincrement=False, nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["store_id"], ["myeclpay_store.id"], name="myeclpay_seller_store_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["core_user.id"], name="myeclpay_seller_user_id_fkey",
        ),
        sa.PrimaryKeyConstraint("user_id", "store_id", name="myeclpay_seller_pkey"),
    )
    op.create_table(
        "myeclpay_user_payment",
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("wallet_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "accepted_tos_signature",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "accepted_tos_version", sa.INTEGER(), autoincrement=False, nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["core_user.id"], name="myeclpay_user_payment_user_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["myeclpay_wallet.id"],
            name="myeclpay_user_payment_wallet_id_fkey",
        ),
        sa.PrimaryKeyConstraint("user_id", name="myeclpay_user_payment_pkey"),
        sa.UniqueConstraint("wallet_id", name="myeclpay_user_payment_wallet_id_key"),
    )
    op.create_table(
        "myeclpay_withdrawal",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("wallet_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("total", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "creation", postgresql.TIMESTAMP(), autoincrement=False, nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["myeclpay_wallet.id"],
            name="myeclpay_withdrawal_wallet_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="myeclpay_withdrawal_pkey"),
    )
    op.create_table(
        "myeclpay_structure_manager_transfer",
        sa.Column("structure_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "confirmation_token", sa.VARCHAR(), autoincrement=False, nullable=False,
        ),
        sa.Column(
            "valid_until", postgresql.TIMESTAMP(), autoincrement=False, nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["structure_id"],
            ["myeclpay_structure.id"],
            name="myeclpay_structure_manager_transfer_structure_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["core_user.id"],
            name="myeclpay_structure_manager_transfer_user_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "structure_id", name="myeclpay_structure_manager_transfer_pkey",
        ),
        sa.UniqueConstraint(
            "confirmation_token",
            name="myeclpay_structure_manager_transfer_confirmation_token_key",
        ),
    )
    op.create_table(
        "myeclpay_used_qrcode",
        sa.Column("qr_code_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("qr_code_tot", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "qr_code_iat", postgresql.TIMESTAMP(), autoincrement=False, nullable=True,
        ),
        sa.Column("qr_code_key", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("qr_code_store", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("signature", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("qr_code_id", name="myeclpay_used_qrcode_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "myeclpay_structure",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("short_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "siege_address_street", sa.VARCHAR(), autoincrement=False, nullable=False,
        ),
        sa.Column(
            "siege_address_city", sa.VARCHAR(), autoincrement=False, nullable=False,
        ),
        sa.Column(
            "siege_address_zipcode", sa.VARCHAR(), autoincrement=False, nullable=False,
        ),
        sa.Column(
            "siege_address_country", sa.VARCHAR(), autoincrement=False, nullable=False,
        ),
        sa.Column("siret", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("iban", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("bic", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("manager_user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "creation", postgresql.TIMESTAMP(), autoincrement=False, nullable=False,
        ),
        sa.Column(
            "association_membership_id", sa.UUID(), autoincrement=False, nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["association_membership_id"],
            ["core_association_membership.id"],
            name="myeclpay_structure_association_membership_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["manager_user_id"],
            ["core_user.id"],
            name="myeclpay_structure_manager_user_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="myeclpay_structure_pkey"),
        sa.UniqueConstraint("name", name="myeclpay_structure_name_key"),
        sa.UniqueConstraint("short_id", name="myeclpay_structure_short_id_key"),
    )
    op.create_table(
        "myeclpay_transaction",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("debited_wallet_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "debited_wallet_device_id", sa.UUID(), autoincrement=False, nullable=False,
        ),
        sa.Column("credited_wallet_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "transaction_type",
            postgresql.ENUM("DIRECT", "REQUEST", "REFUND", name="transactiontype"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("seller_user_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("total", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "creation", postgresql.TIMESTAMP(), autoincrement=False, nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "CONFIRMED", "CANCELED", "REFUNDED", "PENDING", name="transactionstatus",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("store_note", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("qr_code_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["credited_wallet_id"],
            ["myeclpay_wallet.id"],
            name="myeclpay_transaction_credited_wallet_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["debited_wallet_device_id"],
            ["myeclpay_wallet_device.id"],
            name="myeclpay_transaction_debited_wallet_device_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["debited_wallet_id"],
            ["myeclpay_wallet.id"],
            name="myeclpay_transaction_debited_wallet_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["qr_code_id"],
            ["myeclpay_used_qrcode.qr_code_id"],
            name="myeclpay_transaction_qr_code_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["seller_user_id"],
            ["core_user.id"],
            name="myeclpay_transaction_seller_user_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="myeclpay_transaction_pkey"),
    )
    op.drop_table("mypayment_seller")
    op.drop_table("mypayment_request")
    op.drop_table("mypayment_invoice_detail")
    op.drop_table("mypayment_structure_manager_transfer")
    op.drop_table("mypayment_store")
    op.drop_table("mypayment_refund")
    op.drop_table("mypayment_invoice")
    op.drop_table("mypayment_user_payment")
    op.drop_table("mypayment_transfer")
    op.drop_table("mypayment_transaction")
    op.drop_table("mypayment_structure")
    op.drop_table("mypayment_withdrawal")
    op.drop_table("mypayment_wallet_device")
    op.drop_table("mypayment_wallet")
    op.drop_table("mypayment_used_qrcode")
    # ### end Alembic commands ###


def pre_test_upgrade(
    alembic_runner: "MigrationContext",
    alembic_connection: sa.Connection,
) -> None:
    pass


def test_upgrade(
    alembic_runner: "MigrationContext",
    alembic_connection: sa.Connection,
) -> None:
    pass
