"""permissions

Create Date: 2025-03-10 21:30:48.890171
"""

from collections.abc import Sequence
from enum import Enum
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pytest_alembic import MigrationContext

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1051d705419e"
down_revision: str | None = "12ceba87cf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


class AccountType(str, Enum):
    """
    Various account types that can be created in Hyperion.
    Each account type is associated with a set of permissions.
    """

    student = "student"
    former_student = "former_student"
    staff = "staff"
    association = "association"
    external = "external"
    other_school_student = "other_school_student"
    demo = "demo"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "core_permission_group",
        sa.Column("permission_name", sa.String(), nullable=False, index=True),
        sa.Column("group_id", sa.String(), nullable=False, index=True),
        sa.ForeignKeyConstraint(["group_id"], ["core_group.id"]),
        sa.PrimaryKeyConstraint("permission_name", "group_id"),
    )
    op.create_table(
        "core_permission_account_type",
        sa.Column("permission_name", sa.String(), nullable=False, index=True),
        sa.Column(
            "account_type",
            postgresql.ENUM(
                AccountType,
                name="accounttype",
                create_type=False,
            ),
            nullable=False,
            index=True,
        ),
    )
    op.drop_table("campaign_voter_groups")
    op.drop_table("module_account_type_visibility")
    op.drop_table("module_group_visibility")
    op.execute("DELETE FROM core_data WHERE schema='ModuleVisibilityAwareness'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campaign_voter_groups",
        sa.Column("group_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("group_id", name="campaign_voter_groups_pkey"),
    )
    op.create_table(
        "module_account_type_visibility",
        sa.Column("root", sa.String(), nullable=False, index=True),
        sa.Column(
            "allowed_account_type",
            postgresql.ENUM(
                AccountType,
                name="accounttype",
                create_type=False,
            ),
            nullable=False,
            index=True,
        ),
        sa.PrimaryKeyConstraint("root", "allowed_account_type"),
    )
    op.create_table(
        "module_group_visibility",
        sa.Column("root", sa.String(), nullable=False, index=True),
        sa.Column("allowed_group_id", sa.String(), nullable=False, index=True),
        sa.PrimaryKeyConstraint("root", "allowed_group_id"),
    )
    op.drop_table("core_permission_group")
    op.drop_table("core_permission_account_type")
    op.execute("DELETE FROM core_data WHERE schema='ModuleVisibilityAwareness'")
    # ### end Alembic commands ###


def pre_test_upgrade(
    alembic_runner: "MigrationContext",
    alembic_connection: sa.Connection,
) -> None:
    pass


def test_upgrade(
    alembic_runner: "MigrationContext",
    alembic_connection: sa.Connection,
) -> None:
    pass
