"""phonebook

Revision ID: 6afc765adaa2
Revises: f17e6182b0a9
Create Date: 2024-02-29 11:46:46.895113

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6afc765adaa2"
down_revision: str | None = "3f9843f165e9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "phonebook_association",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("mandate_year", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_phonebook_association_id"),
        "phonebook_association",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_phonebook_association_name"),
        "phonebook_association",
        ["name"],
        unique=False,
    )
    op.create_table(
        "phonebook_membership",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("association_id", sa.String(), nullable=False),
        sa.Column("mandate_year", sa.Integer(), nullable=False),
        sa.Column("role_name", sa.String(), nullable=False),
        sa.Column("role_tags", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["association_id"],
            ["phonebook_association.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["core_user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "association_id", "mandate_year"),
    )
    op.create_index(
        op.f("ix_phonebook_membership_id"),
        "phonebook_membership",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_phonebook_membership_id"), table_name="phonebook_membership")
    op.drop_table("phonebook_membership")
    op.drop_index(
        op.f("ix_phonebook_association_name"),
        table_name="phonebook_association",
    )
    op.drop_index(
        op.f("ix_phonebook_association_id"),
        table_name="phonebook_association",
    )
    op.drop_table("phonebook_association")
    # ### end Alembic commands ###
