"""PMF

Create Date: 2025-11-22 19:49:38.136247
"""

from collections.abc import Sequence
from typing import TYPE_CHECKING, Union

if TYPE_CHECKING:
    from pytest_alembic import MigrationContext

import sqlalchemy as sa
from alembic import op

from app.types.sqlalchemy import TZDateTime

# revision identifiers, used by Alembic.
revision: str = "ca5a9c9c64e5"
down_revision: str | None = "9fc3dc926600"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pmf_tags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tag", sa.String(), nullable=False),
        sa.Column("created_at", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pmf_offers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.String(), nullable=False),
        sa.Column("company_name", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column(
            "offer_type",
            sa.Enum("TFE", "APP", "EXE", "CDI", "CDD", name="offertype"),
            nullable=False,
        ),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column(
            "location_type",
            sa.Enum("On_site", "Hybrid", "Remote", name="locationtype"),
            nullable=False,
        ),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["core_user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pmf_offer_tags",
        sa.Column("offer_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["offer_id"], ["pmf_offers.id"]),
        sa.ForeignKeyConstraint(["tag_id"], ["pmf_tags.id"]),
        sa.PrimaryKeyConstraint("offer_id", "tag_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pmf_offer_tags")
    op.drop_table("pmf_offers")
    op.drop_table("pmf_tags")
    # ### end Alembic commands ###


def pre_test_upgrade(
    alembic_runner: "MigrationContext",
    alembic_connection: sa.Connection,
) -> None:
    pass


def test_upgrade(
    alembic_runner: "MigrationContext",
    alembic_connection: sa.Connection,
) -> None:
    pass
