"""56-ticketing

Create Date: 2026-02-18 00:43:05.909471
"""

from collections.abc import Sequence
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pytest_alembic import MigrationContext

import sqlalchemy as sa
from alembic import op

from app.types.sqlalchemy import TZDateTime

# revision identifiers, used by Alembic.
revision: str = "321017e1de7f"
down_revision: str | None = "562adbd796ae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ticketing_event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.Column("creator_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("open_date", TZDateTime(), nullable=False),
        sa.Column("close_date", TZDateTime(), nullable=True),
        sa.Column("quota", sa.Integer(), nullable=True),
        sa.Column("used_quota", sa.Integer(), nullable=False),
        sa.Column("user_quota", sa.Integer(), nullable=True),
        sa.Column("disabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["creator_id"], ["core_user.id"]),
        sa.ForeignKeyConstraint(["store_id"], ["mypayment_store.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ticketing_category",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("required_mebership", sa.Uuid(), nullable=True),
        sa.Column("quota", sa.Integer(), nullable=True),
        sa.Column("used_quota", sa.Integer(), nullable=False),
        sa.Column("user_quota", sa.Integer(), nullable=True),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("disabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["ticketing_event.id"]),
        sa.ForeignKeyConstraint(
            ["required_mebership"], ["core_association_membership.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ticketing_session",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("quota", sa.Integer(), nullable=True),
        sa.Column("used_quota", sa.Integer(), nullable=False),
        sa.Column("user_quota", sa.Integer(), nullable=True),
        sa.Column("disabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["ticketing_event.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ticketing_category_session",
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["ticketing_category.id"]),
        sa.ForeignKeyConstraint(["session_id"], ["ticketing_session.id"]),
        sa.PrimaryKeyConstraint("category_id", "session_id"),
    )
    op.create_table(
        "ticketing_ticket",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("created_at", TZDateTime(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("nb_scan", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["ticketing_category.id"]),
        sa.ForeignKeyConstraint(["event_id"], ["ticketing_event.id"]),
        sa.ForeignKeyConstraint(["session_id"], ["ticketing_session.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["core_user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ticketing_ticket")
    op.drop_table("ticketing_category_session")
    op.drop_table("ticketing_session")
    op.drop_table("ticketing_category")
    op.drop_table("ticketing_event")
    # ### end Alembic commands ###


def pre_test_upgrade(
    alembic_runner: "MigrationContext",
    alembic_connection: sa.Connection,
) -> None:
    pass


def test_upgrade(
    alembic_runner: "MigrationContext",
    alembic_connection: sa.Connection,
) -> None:
    pass
