"""UnregisteredRecoveryRequests

Create Date: 2026-05-30 14:03:43.757430
"""

from collections.abc import Sequence
from enum import StrEnum
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pytest_alembic import MigrationContext

import sqlalchemy as sa
from alembic import op

from app.types.sqlalchemy import TZDateTime

# revision identifiers, used by Alembic.
revision: str = "84ee3296cc58"
down_revision: str | None = "7dbe3290e145"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


class DocumentStatus(StrEnum):
    DRAFT = "DRAFT"
    PENDING = "PENDING"
    COMPLETED = "COMPLETED"
    REJECTED = "REJECTED"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "document_team",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("api_key", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["core_group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("team_id"),
    )

    op.create_table(
        "document_template",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("documenso_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", TZDateTime(), nullable=False),
        sa.Column("updated_at", TZDateTime(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("document_directory_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["document_team.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("documenso_id"),
    )

    op.create_table(
        "document_document",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("documenso_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("module", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("signing_token", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                DocumentStatus,
                name="documentstatus",
            ),
            nullable=False,
        ),
        sa.Column("created_at", TZDateTime(), nullable=False),
        sa.Column("updated_at", TZDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["document_template.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["core_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("documenso_id"),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("document_document")
    op.drop_table("document_template")
    op.drop_table("document_team")
    sa.Enum(name="documentstatus").drop(op.get_bind(), checkfirst=False)


def pre_test_upgrade(
    alembic_runner: "MigrationContext",
    alembic_connection: sa.Connection,
) -> None:
    pass


def test_upgrade(
    alembic_runner: "MigrationContext",
    alembic_connection: sa.Connection,
) -> None:
    pass
