"""empty message

Create Date: 2026-03-19 15:49:33.554684
"""

from collections.abc import Sequence
from enum import Enum
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pytest_alembic import MigrationContext

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "46fbbcee7237"
down_revision: str | None = "7dbe3290e145"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


class TransferOrigin(Enum):
    HELLO_ASSO = "HELLO_ASSO"
    CHECK = "CHECK"
    CASH = "CASH"
    BANK_TRANSFER = "BANK_TRANSFER"


class TransferType(Enum):
    HELLO_ASSO = "HELLO_ASSO"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("mypayment_request", sa.Column("module", sa.String(), nullable=False))
    op.add_column(
        "mypayment_request",
        sa.Column("object_id", sa.Uuid(), nullable=False),
    )
    op.drop_column("mypayment_request", "callback")
    op.add_column("mypayment_transfer", sa.Column("module", sa.String(), nullable=True))
    op.add_column(
        "mypayment_transfer",
        sa.Column("object_id", sa.Uuid(), nullable=True),
    )
    op.add_column(
        "mypayment_seller",
        sa.Column("can_manage_events", sa.Boolean(), nullable=False),
    )
    op.alter_column(
        "mypayment_transaction",
        "debited_wallet_device_id",
        existing_type=sa.UUID(),
        nullable=True,
    )
    postgresql.ENUM(TransferOrigin, name="transferorigin").create(op.get_bind())
    op.alter_column(
        "mypayment_transfer",
        "type",
        new_column_name="origin",
        type_=sa.Enum(TransferOrigin, name="transferorigin"),
        existing_type=sa.Enum(TransferType, name="transfertype"),
        postgresql_using="type::text::transferorigin",
    )
    sa.Enum(TransferType, name="transfertype").drop(op.get_bind())

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mypayment_transfer", "object_id")
    op.drop_column("mypayment_transfer", "module")
    op.add_column(
        "mypayment_request",
        sa.Column("callback", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("mypayment_request", "module")
    op.drop_column("mypayment_request", "object_id")
    op.drop_column("mypayment_seller", "can_manage_events")
    op.alter_column(
        "mypayment_transaction",
        "debited_wallet_device_id",
        existing_type=sa.UUID(),
        nullable=False,
    )
    postgresql.ENUM(
        TransferType,
        name="transfertype",
    ).create(op.get_bind())
    op.alter_column(
        "mypayment_transfer",
        "origin",
        existing_type=sa.Enum(TransferOrigin, name="transferorigin"),
        type_=sa.Enum(TransferType, name="transfertype"),
        new_column_name="type",
        postgresql_using="origin::text::transfertype",
    )
    sa.Enum(TransferOrigin, name="transferorigin").drop(op.get_bind())

    # ### end Alembic commands ###


def pre_test_upgrade(
    alembic_runner: "MigrationContext",
    alembic_connection: sa.Connection,
) -> None:
    pass


def test_upgrade(
    alembic_runner: "MigrationContext",
    alembic_connection: sa.Connection,
) -> None:
    pass
