"""UnregisteredRecoveryRequests

Create Date: 2026-05-30 14:03:43.757430
"""

from collections.abc import Sequence
from enum import StrEnum
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pytest_alembic import MigrationContext

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "21ee852eac58"
down_revision: str | None = "84ee3296cc58"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


class DocumentStatus(StrEnum):
    DRAFT = "DRAFT"
    PENDING = "PENDING"
    COMPLETED = "COMPLETED"
    REJECTED = "REJECTED"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "core_association_membership",
        sa.Column("template_id", sa.Uuid(), nullable=True),
    )
    op.create_foreign_key(
        "core_association_membership_template_id_fkey",
        "core_association_membership",
        "document_template",
        ["template_id"],
        ["id"],
    )
    op.add_column(
        "core_association_user_membership",
        sa.Column("document_id", sa.Uuid(), nullable=True),
    )
    op.add_column(
        "core_association_user_membership",
        sa.Column(
            "document_status",
            sa.Enum(
                DocumentStatus,
                name="documentstatus",
            ),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        "core_association_user_membership_document_id_fkey",
        "core_association_user_membership",
        "document_document",
        ["document_id"],
        ["id"],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "core_association_user_membership_document_id_fkey",
        "core_association_user_membership",
        type_="foreignkey",
    )
    op.drop_column("core_association_user_membership", "document_status")
    op.drop_column("core_association_user_membership", "document_id")
    op.drop_constraint(
        "core_association_membership_template_id_fkey",
        "core_association_membership",
        type_="foreignkey",
    )


def pre_test_upgrade(
    alembic_runner: "MigrationContext",
    alembic_connection: sa.Connection,
) -> None:
    pass


def test_upgrade(
    alembic_runner: "MigrationContext",
    alembic_connection: sa.Connection,
) -> None:
    pass
