"""empty message

Create Date: 2026-08-14 23:34:02.175178
"""

from collections.abc import Sequence
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pytest_alembic import MigrationContext

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2b6eae542913"
down_revision: str | None = "ca69342eac58"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_raid_participant_checkout_id",
        table_name="raid_participant_checkout",
    )
    op.drop_table("raid_participant_checkout")
    op.drop_index("ix_raid_invite_id", table_name="raid_invite")
    op.drop_table("raid_invite")
    op.drop_index("ix_raid_team_id", table_name="raid_team")
    op.drop_table("raid_team")
    op.drop_index("ix_raid_participant_id", table_name="raid_participant")
    op.drop_table("raid_participant")
    op.drop_index("ix_raid_security_file_id", table_name="raid_security_file")
    op.drop_table("raid_security_file")
    op.drop_index("ix_raid_document_id", table_name="raid_document")
    op.drop_table("raid_document")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "raid_team",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "difficulty",
            postgresql.ENUM("discovery", "sports", "expert", name="difficulty"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("captain_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("second_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("number", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "meeting_place",
            postgresql.ENUM("centrale", "bellecour", "anyway", name="meetingplace"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("file_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["captain_id"],
            ["raid_participant.id"],
            name="raid_team_captain_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["second_id"],
            ["raid_participant.id"],
            name="raid_team_second_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="raid_team_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index("ix_raid_team_id", "raid_team", ["id"], unique=False)
    op.create_table(
        "raid_invite",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("team_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("token", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["raid_team.id"],
            name="raid_invite_team_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="raid_invite_pkey"),
    )
    op.create_index("ix_raid_invite_id", "raid_invite", ["id"], unique=False)
    op.create_table(
        "raid_participant_checkout",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("participant_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("checkout_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["checkout_id"],
            ["checkout_checkout.id"],
            name="raid_participant_checkout_checkout_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["raid_participant.id"],
            name="raid_participant_checkout_participant_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="raid_participant_checkout_pkey"),
    )
    op.create_index(
        "ix_raid_participant_checkout_id",
        "raid_participant_checkout",
        ["id"],
        unique=False,
    )
    op.create_table(
        "raid_document",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("uploaded_at", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM(
                "idCard",
                "medicalCertificate",
                "studentCard",
                "raidRules",
                "parentAuthorization",
                name="documenttype",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "validation",
            postgresql.ENUM(
                "pending",
                "accepted",
                "refused",
                "temporary",
                name="documentvalidation",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="raid_document_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index("ix_raid_document_id", "raid_document", ["id"], unique=False)
    op.create_table(
        "raid_security_file",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("allergy", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("asthma", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "intensive_care_unit",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "intensive_care_unit_when",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "ongoing_treatment",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("sicknesses", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("hospitalization", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "surgical_operation",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("trauma", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("family", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "emergency_person_firstname",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "emergency_person_name",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "emergency_person_phone",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("file_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="raid_security_file_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        "ix_raid_security_file_id",
        "raid_security_file",
        ["id"],
        unique=False,
    )
    op.create_table(
        "raid_participant",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("firstname", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("birthday", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("phone", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("address", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "bike_size",
            postgresql.ENUM("XS", "S", "M", "L", "XL", "None_", name="size"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "t_shirt_size",
            postgresql.ENUM("XS", "S", "M", "L", "XL", "None_", name="size"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("situation", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("other_school", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("company", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("diet", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("id_card_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "medical_certificate_id",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("security_file_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("student_card_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("raid_rules_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "parent_authorization_id",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "attestation_on_honour",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("payment", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("t_shirt_payment", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("is_minor", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["id_card_id"],
            ["raid_document.id"],
            name="raid_participant_id_card_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["medical_certificate_id"],
            ["raid_document.id"],
            name="raid_participant_medical_certificate_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["parent_authorization_id"],
            ["raid_document.id"],
            name="raid_participant_parent_authorization_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["raid_rules_id"],
            ["raid_document.id"],
            name="raid_participant_raid_rules_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["security_file_id"],
            ["raid_security_file.id"],
            name="raid_participant_security_file_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["student_card_id"],
            ["raid_document.id"],
            name="raid_participant_student_card_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="raid_participant_pkey"),
    )
    op.create_index("ix_raid_participant_id", "raid_participant", ["id"], unique=False)
    # ### end Alembic commands ###


def pre_test_upgrade(
    alembic_runner: "MigrationContext",
    alembic_connection: sa.Connection,
) -> None:
    pass


def test_upgrade(
    alembic_runner: "MigrationContext",
    alembic_connection: sa.Connection,
) -> None:
    pass
