"""empty message

Create Date: 2026-08-14 23:38:34.379180
"""

from collections.abc import Sequence
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pytest_alembic import MigrationContext

import sqlalchemy as sa
from alembic import op

from app.types.sqlalchemy import TZDateTime

# revision identifiers, used by Alembic.
revision: str = "ee92f619275e"
down_revision: str | None = "2b6eae542913"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "raid_edition",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("registering_end_date", sa.Date(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("inscription_enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "raid_document",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("edition_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("uploaded_at", sa.Date(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "idCard",
                "medicalCertificate",
                "studentCard",
                "raidRules",
                "parentAuthorization",
                name="documenttype",
            ),
            nullable=False,
        ),
        sa.Column(
            "validation",
            sa.Enum(
                "pending",
                "accepted",
                "refused",
                "temporary",
                name="documentvalidation",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["edition_id"], ["raid_edition.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_raid_document_id"), "raid_document", ["id"], unique=False)
    op.create_table(
        "raid_security_file",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("edition_id", sa.Uuid(), nullable=False),
        sa.Column("allergy", sa.String(), nullable=True),
        sa.Column("asthma", sa.Boolean(), nullable=False),
        sa.Column("intensive_care_unit", sa.Boolean(), nullable=True),
        sa.Column("intensive_care_unit_when", sa.String(), nullable=True),
        sa.Column("ongoing_treatment", sa.String(), nullable=True),
        sa.Column("sicknesses", sa.String(), nullable=True),
        sa.Column("hospitalization", sa.String(), nullable=True),
        sa.Column("surgical_operation", sa.String(), nullable=True),
        sa.Column("trauma", sa.String(), nullable=True),
        sa.Column("family", sa.String(), nullable=True),
        sa.Column("emergency_person_firstname", sa.String(), nullable=True),
        sa.Column("emergency_person_name", sa.String(), nullable=True),
        sa.Column("emergency_person_phone", sa.String(), nullable=True),
        sa.Column("file_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["edition_id"], ["raid_edition.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_raid_security_file_id"),
        "raid_security_file",
        ["id"],
        unique=False,
    )
    op.create_table(
        "raid_participant",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("edition_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "submitted",
                "validated",
                "cancelled",
                name="raidregistrationstatus",
            ),
            nullable=False,
        ),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column(
            "bike_size",
            sa.Enum("XS", "S", "M", "L", "XL", "None_", name="size"),
            nullable=True,
        ),
        sa.Column(
            "t_shirt_size",
            sa.Enum("XS", "S", "M", "L", "XL", "None_", name="size"),
            nullable=True,
        ),
        sa.Column(
            "situation",
            sa.Enum(
                "centrale",
                "otherSchool",
                "corporatePartner",
                "other",
                name="situation",
            ),
            nullable=True,
        ),
        sa.Column("other_school", sa.String(), nullable=True),
        sa.Column("company", sa.String(), nullable=True),
        sa.Column("diet", sa.String(), nullable=True),
        sa.Column("id_card_id", sa.String(), nullable=True),
        sa.Column("medical_certificate_id", sa.String(), nullable=True),
        sa.Column("security_file_id", sa.String(), nullable=True),
        sa.Column("student_card_id", sa.String(), nullable=True),
        sa.Column("raid_rules_id", sa.String(), nullable=True),
        sa.Column("parent_authorization_id", sa.String(), nullable=True),
        sa.Column("attestation_on_honour", sa.Boolean(), nullable=False),
        sa.Column("payment", sa.Boolean(), nullable=False),
        sa.Column("t_shirt_payment", sa.Boolean(), nullable=False),
        sa.Column("is_minor", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["edition_id"], ["raid_edition.id"]),
        sa.ForeignKeyConstraint(["id_card_id"], ["raid_document.id"]),
        sa.ForeignKeyConstraint(["medical_certificate_id"], ["raid_document.id"]),
        sa.ForeignKeyConstraint(["parent_authorization_id"], ["raid_document.id"]),
        sa.ForeignKeyConstraint(["raid_rules_id"], ["raid_document.id"]),
        sa.ForeignKeyConstraint(["security_file_id"], ["raid_security_file.id"]),
        sa.ForeignKeyConstraint(["student_card_id"], ["raid_document.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["core_user.id"]),
        sa.PrimaryKeyConstraint("user_id", "edition_id"),
    )
    op.create_index(
        op.f("ix_raid_participant_user_id"),
        "raid_participant",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "raid_volunteer",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("edition_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", TZDateTime(), nullable=False),
        sa.Column("validated", sa.Boolean(), nullable=False),
        sa.Column("cancelled", sa.Boolean(), nullable=False),
        sa.Column("diet", sa.String(), nullable=True),
        sa.Column("allergy", sa.String(), nullable=True),
        sa.Column(
            "t_shirt_size",
            sa.Enum("XS", "S", "M", "L", "XL", "None_", name="size"),
            nullable=True,
        ),
        sa.Column("emergency_person_name", sa.String(), nullable=True),
        sa.Column("emergency_person_phone", sa.String(), nullable=True),
        sa.Column("has_car", sa.Boolean(), nullable=False),
        sa.Column("car_seats", sa.Integer(), nullable=True),
        sa.Column("is_special_driver", sa.Boolean(), nullable=False),
        sa.Column("is_utility_vehicle_driver", sa.Boolean(), nullable=False),
        sa.Column("is_parcours_helper", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["edition_id"], ["raid_edition.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["core_user.id"]),
        sa.PrimaryKeyConstraint("user_id", "edition_id"),
    )
    op.create_table(
        "raid_participant_checkout",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("participant_user_id", sa.String(), nullable=False),
        sa.Column("edition_id", sa.Uuid(), nullable=False),
        sa.Column("checkout_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["checkout_id"], ["checkout_checkout.id"]),
        sa.ForeignKeyConstraint(
            ["participant_user_id", "edition_id"],
            ["raid_participant.user_id", "raid_participant.edition_id"],
            name="fk_raid_participant_checkout_participant",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_raid_participant_checkout_id"),
        "raid_participant_checkout",
        ["id"],
        unique=False,
    )
    op.create_table(
        "raid_team",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("edition_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "difficulty",
            sa.Enum("discovery", "sports", "expert", name="difficulty"),
            nullable=True,
        ),
        sa.Column("captain_id", sa.String(), nullable=False),
        sa.Column("second_id", sa.String(), nullable=True),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column(
            "meeting_place",
            sa.Enum("centrale", "bellecour", "anyway", name="meetingplace"),
            nullable=True,
        ),
        sa.Column("file_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["captain_id", "edition_id"],
            ["raid_participant.user_id", "raid_participant.edition_id"],
            name="fk_raid_team_captain",
        ),
        sa.ForeignKeyConstraint(["edition_id"], ["raid_edition.id"]),
        sa.ForeignKeyConstraint(
            ["second_id", "edition_id"],
            ["raid_participant.user_id", "raid_participant.edition_id"],
            name="fk_raid_team_second",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "second_id",
            "edition_id",
            name="uq_raid_team_second_id_edition_id",
        ),
    )
    op.create_index(op.f("ix_raid_team_id"), "raid_team", ["id"], unique=False)
    op.create_table(
        "raid_invite",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("edition_id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.String(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["edition_id"], ["raid_edition.id"]),
        sa.ForeignKeyConstraint(["team_id"], ["raid_team.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_raid_invite_id"), "raid_invite", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_raid_invite_id"), table_name="raid_invite")
    op.drop_table("raid_invite")
    op.drop_index(op.f("ix_raid_team_id"), table_name="raid_team")
    op.drop_table("raid_team")
    op.drop_index(
        op.f("ix_raid_participant_checkout_id"),
        table_name="raid_participant_checkout",
    )
    op.drop_table("raid_participant_checkout")
    op.drop_table("raid_volunteer")
    op.drop_index(op.f("ix_raid_participant_user_id"), table_name="raid_participant")
    op.drop_table("raid_participant")
    op.drop_index(op.f("ix_raid_security_file_id"), table_name="raid_security_file")
    op.drop_table("raid_security_file")
    op.drop_index(op.f("ix_raid_document_id"), table_name="raid_document")
    op.drop_table("raid_document")
    op.drop_table("raid_edition")
    # ### end Alembic commands ###


def pre_test_upgrade(
    alembic_runner: "MigrationContext",
    alembic_connection: sa.Connection,
) -> None:
    pass


def test_upgrade(
    alembic_runner: "MigrationContext",
    alembic_connection: sa.Connection,
) -> None:
    pass
