"""Add MyECLPay payment type to CdR

Create Date: 2026-07-25 23:45:05.679962
"""

from collections.abc import Sequence
from enum import Enum
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pytest_alembic import MigrationContext

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dd905b1f5f57"
down_revision: str | None = "ee92f619275e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


class PaymentType(Enum):
    cash = "cash"
    check = "check"
    helloasso = "HelloAsso"
    card = "card"
    archived = "archived"
    myeclpay = "MyECLPay"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute(
            f"ALTER TYPE paymenttype ADD VALUE IF NOT EXISTS '{PaymentType.myeclpay.value}';",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        f"UPDATE cdr_payment SET payment_type = '{PaymentType.archived.value}' WHERE payment_type = '{PaymentType.myeclpay.value}';",
    )
    # ### end Alembic commands ###


def pre_test_upgrade(
    alembic_runner: "MigrationContext",
    alembic_connection: sa.Connection,
) -> None:
    pass


def test_upgrade(
    alembic_runner: "MigrationContext",
    alembic_connection: sa.Connection,
) -> None:
    pass
