"""Add MyECLPay payment type to CdR

Create Date: 2026-07-25 23:45:05.679962
"""

from collections.abc import Sequence
from enum import Enum
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pytest_alembic import MigrationContext

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dd905b1f5f57"
down_revision: str | None = "ee92f619275e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


class PaymentType(Enum):
    cash = "cash"
    check = "check"
    helloasso = "HelloAsso"
    card = "card"
    archived = "archived"
    myeclpay = "MyECLPay"


paymentTable = sa.Table(
    "cdr_payment",
    sa.MetaData(),
    sa.Column("id", sa.Uuid(), primary_key=True, nullable=False),
    sa.Column("payment_type", sa.Enum(PaymentType), nullable=False),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        f"ALTER TYPE paymenttype ADD VALUE IF NOT EXISTS '{PaymentType.myeclpay.name}';",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    data = conn.execute(
        sa.select(paymentTable),
    ).fetchall()
    for row in data:
        if row.payment_type == PaymentType.myeclpay:
            conn.execute(
                sa.update(paymentTable)
                .where(paymentTable.c.id == row.id)
                .values(payment_type=PaymentType.archived),
            )

    # ### end Alembic commands ###


def pre_test_upgrade(
    alembic_runner: "MigrationContext",
    alembic_connection: sa.Connection,
) -> None:
    pass


def test_upgrade(
    alembic_runner: "MigrationContext",
    alembic_connection: sa.Connection,
) -> None:
    pass
