"""empty message

Create Date: 2026-03-19 15:49:33.554684
"""

from collections.abc import Sequence
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pytest_alembic import MigrationContext

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46fbbcee7237"
down_revision: str | None = "562adbd796ae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("mypayment_request", sa.Column("module", sa.String(), nullable=False))
    op.add_column(
        "mypayment_request",
        sa.Column("object_id", sa.Uuid(), nullable=False),
    )
    op.drop_column("mypayment_request", "callback")
    op.add_column("mypayment_transfer", sa.Column("module", sa.String(), nullable=True))
    op.add_column(
        "mypayment_transfer",
        sa.Column("object_id", sa.Uuid(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mypayment_transfer", "object_id")
    op.drop_column("mypayment_transfer", "module")
    op.add_column(
        "mypayment_request",
        sa.Column("callback", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("mypayment_request", "module")
    op.drop_column("mypayment_request", "object_id")
    # ### end Alembic commands ###


def pre_test_upgrade(
    alembic_runner: "MigrationContext",
    alembic_connection: sa.Connection,
) -> None:
    pass


def test_upgrade(
    alembic_runner: "MigrationContext",
    alembic_connection: sa.Connection,
) -> None:
    pass
