"""empty message

Create Date: 2026-03-19 15:49:33.554684
"""

from collections.abc import Sequence
from typing import TYPE_CHECKING
from uuid import uuid4

if TYPE_CHECKING:
    from pytest_alembic import MigrationContext

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46fbbcee7237"
down_revision: str | None = "146db8dcb23e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


wallet_id = uuid4()
transfer_id = uuid4()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("mypayment_request", sa.Column("module", sa.String(), nullable=False))
    op.add_column(
        "mypayment_request",
        sa.Column("object_id", sa.Uuid(), nullable=False),
    )
    op.drop_column("mypayment_request", "callback")
    op.add_column("mypayment_transfer", sa.Column("module", sa.String(), nullable=True))
    op.add_column(
        "mypayment_transfer",
        sa.Column("object_id", sa.Uuid(), nullable=True),
    )
    op.alter_column(
        "mypayment_transfer",
        "type",
        new_column_name="origin",
    )
    op.execute("ALTER TYPE transfertype RENAME TO transferorigin")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mypayment_transfer", "object_id")
    op.drop_column("mypayment_transfer", "module")
    op.add_column(
        "mypayment_request",
        sa.Column("callback", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("mypayment_request", "module")
    op.drop_column("mypayment_request", "object_id")
    op.execute("ALTER TYPE transferorigin RENAME TO transfertype")
    op.alter_column(
        "mypayment_transfer",
        "origin",
        new_column_name="type",
    )
    # ### end Alembic commands ###


def pre_test_upgrade(
    alembic_runner: "MigrationContext",
    alembic_connection: sa.Connection,
) -> None:
    alembic_runner.insert_into(
        "mypayment_wallet",
        {
            "id": wallet_id,
            "type": "USER",
            "balance": 0,
        },
    )
    alembic_runner.insert_into(
        "mypayment_transfer",
        {
            "id": transfer_id,
            "type": "HELLO_ASSO",
            "transfer_identifier": "test-transfer-identifier",
            "approver_user_id": None,
            "wallet_id": wallet_id,
            "total": 100,
            "creation": "2026-04-18T00:00:00+00:00",
            "confirmed": False,
        },
    )


def test_upgrade(
    alembic_runner: "MigrationContext",
    alembic_connection: sa.Connection,
) -> None:
    has_old_column = alembic_connection.execute(
        sa.text(
            """
            SELECT COUNT(*)
            FROM information_schema.columns
            WHERE table_name = 'mypayment_transfer' AND column_name = 'type'
            """,
        ),
    ).scalar_one()
    assert has_old_column == 0

    has_new_column = alembic_connection.execute(
        sa.text(
            """
            SELECT COUNT(*)
            FROM information_schema.columns
            WHERE table_name = 'mypayment_transfer' AND column_name = 'origin'
            """,
        ),
    ).scalar_one()
    assert has_new_column == 1
