"""Add payment fields to raid_volunteer and create raid_volunteer_checkout table

Create Date: 2026-09-04 14:49:46.689444
"""

from collections.abc import Sequence
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pytest_alembic import MigrationContext

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1638e8a71c27"
down_revision: str | None = "e0e6f306bed7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "raid_volunteer_checkout",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("volunteer_user_id", sa.String(), nullable=False),
        sa.Column("edition_id", sa.Uuid(), nullable=False),
        sa.Column("checkout_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["checkout_id"], ["checkout_checkout.id"]),
        sa.ForeignKeyConstraint(
            ["volunteer_user_id", "edition_id"],
            ["raid_volunteer.user_id", "raid_volunteer.edition_id"],
            name="fk_raid_volunteer_checkout_volunteer",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_raid_volunteer_checkout_id"),
        "raid_volunteer_checkout",
        ["id"],
        unique=False,
    )
    # Add columns with default values for existing rows
    op.add_column(
        "raid_volunteer",
        sa.Column("payment", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "raid_volunteer",
        sa.Column(
            "t_shirt_payment",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("raid_volunteer", "t_shirt_payment")
    op.drop_column("raid_volunteer", "payment")
    op.drop_index(
        op.f("ix_raid_volunteer_checkout_id"),
        table_name="raid_volunteer_checkout",
    )
    op.drop_table("raid_volunteer_checkout")
    # ### end Alembic commands ###


def pre_test_upgrade(
    alembic_runner: "MigrationContext",
    alembic_connection: sa.Connection,
) -> None:
    pass


def test_upgrade(
    alembic_runner: "MigrationContext",
    alembic_connection: sa.Connection,
) -> None:
    pass
