"""69-raid-scholarship-price

Create Date: 2026-09-11 10:28:18.162848
"""

from collections.abc import Sequence
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pytest_alembic import MigrationContext

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cfdbcbca654a"
down_revision: str | None = "1638e8a71c27"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "raid_participant",
        sa.Column("school_authorization_id", sa.String(), nullable=True),
    )
    op.add_column(
        "raid_participant",
        sa.Column(
            "has_scholarship",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.create_foreign_key(
        "raid_participant_school_authorization_id_fkey",
        "raid_participant",
        "raid_document",
        ["school_authorization_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "raid_participant_school_authorization_id_fkey",
        "raid_participant",
        type_="foreignkey",
    )
    op.drop_column("raid_participant", "has_scholarship")
    op.drop_column("raid_participant", "school_authorization_id")
    # ### end Alembic commands ###


def pre_test_upgrade(
    alembic_runner: "MigrationContext",
    alembic_connection: sa.Connection,
) -> None:
    pass


def test_upgrade(
    alembic_runner: "MigrationContext",
    alembic_connection: sa.Connection,
) -> None:
    """Verify the new scholarship columns exist after the upgrade."""
    columns = {
        row[0]
        for row in alembic_connection.execute(
            sa.text(
                "SELECT column_name FROM information_schema.columns "
                "WHERE table_name = 'raid_participant'",
            ),
        ).fetchall()
    }
    assert "school_authorization_id" in columns
    assert "has_scholarship" in columns

    # `has_scholarship` must be NOT NULL with a false default for existing rows.
    row = alembic_connection.execute(
        sa.text(
            "SELECT is_nullable, column_default FROM information_schema.columns "
            "WHERE table_name = 'raid_participant' AND column_name = 'has_scholarship'",
        ),
    ).fetchone()
    assert row is not None
    is_nullable, column_default = row
    assert is_nullable == "NO"
    assert column_default is not None
    assert "false" in column_default.lower()

    # The school authorization column must reference raid_document.
    fk = alembic_connection.execute(
        sa.text(
            "SELECT 1 FROM information_schema.table_constraints tc "
            "JOIN information_schema.key_column_usage kcu "
            "ON tc.constraint_name = kcu.constraint_name "
            "WHERE tc.table_name = 'raid_participant' "
            "AND tc.constraint_type = 'FOREIGN KEY' "
            "AND kcu.column_name = 'school_authorization_id'",
        ),
    ).fetchone()
    assert fk is not None
