"""init

Revision ID: 6aae5801c527
Revises:
Create Date: 2022-04-06 16:08:07.821080

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6aae5801c527"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
