"""empty message

Create Date: 2024-04-27 15:27:25.136075
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.types.sqlalchemy import TZDateTime



# revision identifiers, used by Alembic.
revision: str = '6b3317b60efd'
down_revision: str | None = '0534d0f07976'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raid_emergency_person',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raid_emergency_person_id'), 'raid_emergency_person', ['id'], unique=False)
    op.add_column('raid_participant', sa.Column('emergency_person_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'raid_participant', 'raid_emergency_person', ['emergency_person_id'], ['id'])
    op.alter_column('recommendation', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Uuid(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recommendation', 'id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'raid_participant', type_='foreignkey')
    op.drop_column('raid_participant', 'emergency_person_id')
    op.drop_index(op.f('ix_raid_emergency_person_id'), table_name='raid_emergency_person')
    op.drop_table('raid_emergency_person')
    # ### end Alembic commands ###
