"""empty message

Revision ID: 0534d0f07976
Revises: 4a02570cc225
Create Date: 2024-04-27 12:25:18.883339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0534d0f07976'
down_revision: Union[str, None] = '4a02570cc225'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raid_team', sa.Column('file_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raid_team', 'file_id')
    # ### end Alembic commands ###
