"""empty message

Revision ID: 0534d0f07976
Revises: 4a02570cc225
Create Date: 2024-04-27 12:25:18.883339

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0534d0f07976"
down_revision: Union[str, None] = "4a02570cc225"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("raid_team", sa.Column("file_id", sa.String(), nullable=True))
    op.create_table(
        "raid_emergency_person",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("firstname", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_raid_emergency_person_id"),
        "raid_emergency_person",
        ["id"],
        unique=False,
    )
    op.add_column(
        "raid_security_file",
        sa.Column("emergency_person_id", sa.String(), nullable=True),
    )
    op.create_foreign_key(
        None,
        "raid_security_file",
        "raid_emergency_person",
        ["emergency_person_id"],
        ["id"],
    )
    op.alter_column(
        "recommendation",
        "id",
        existing_type=sa.VARCHAR(),
        type_=sa.Uuid(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("raid_team", "file_id")
    op.alter_column(
        "recommendation",
        "id",
        existing_type=sa.Uuid(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_constraint(None, "raid_security_file", type_="foreignkey")
    op.drop_column("raid_security_file", "emergency_person_id")
    op.drop_index(
        op.f("ix_raid_emergency_person_id"), table_name="raid_emergency_person"
    )
    op.drop_table("raid_emergency_person")
    # ### end Alembic commands ###
