"""raid

Revision ID: 91b29f00c75d
Revises: 28aa5ef44bf3
Create Date: 2024-02-19 18:45:38.481715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91b29f00c75d'
down_revision: Union[str, None] = 'f17e6182b0a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raid_document',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.Date(), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('type', sa.Enum('idCard', 'medicalCertificate', 'studentCard', 'raidRules', name='documenttype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raid_document_id'), 'raid_document', ['id'], unique=False)
    op.create_table('raid_security_file',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('allergy', sa.String(), nullable=True),
    sa.Column('asthma', sa.Boolean(), nullable=False),
    sa.Column('intensive_care_unit', sa.Boolean(), nullable=True),
    sa.Column('intensive_care_unit_when', sa.String(), nullable=True),
    sa.Column('ongoing_treatment', sa.String(), nullable=True),
    sa.Column('sicknesses', sa.String(), nullable=True),
    sa.Column('hospitalization', sa.String(), nullable=True),
    sa.Column('surgical_operation', sa.String(), nullable=True),
    sa.Column('trauma', sa.String(), nullable=True),
    sa.Column('family', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raid_security_file_id'), 'raid_security_file', ['id'], unique=False)
    op.create_table('raid_participant',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('bike_size', sa.Enum('XS', 'S', 'M', 'L', 'XL', name='size'), nullable=False),
    sa.Column('t_shirt_size', sa.Enum('XS', 'S', 'M', 'L', 'XL', name='size'), nullable=False),
    sa.Column('situation', sa.String(), nullable=False),
    sa.Column('other_school', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('diet', sa.String(), nullable=True),
    sa.Column('id_card_id', sa.String(), nullable=False),
    sa.Column('medical_certificate_id', sa.String(), nullable=False),
    sa.Column('security_file_id', sa.String(), nullable=True),
    sa.Column('student_card_id', sa.String(), nullable=True),
    sa.Column('raid_rules_id', sa.String(), nullable=False),
    sa.Column('attestation_on_honour', sa.Boolean(), nullable=False),
    sa.Column('validation_progress', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_card_id'], ['raid_document.id'], ),
    sa.ForeignKeyConstraint(['medical_certificate_id'], ['raid_document.id'], ),
    sa.ForeignKeyConstraint(['raid_rules_id'], ['raid_document.id'], ),
    sa.ForeignKeyConstraint(['security_file_id'], ['raid_security_file.id'], ),
    sa.ForeignKeyConstraint(['student_card_id'], ['raid_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raid_participant_id'), 'raid_participant', ['id'], unique=False)
    op.create_table('raid_team',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Enum('discovery', 'sports', 'expert', name='difficulty'), nullable=True),
    sa.Column('captain_id', sa.String(), nullable=False),
    sa.Column('second_id', sa.String(), nullable=True),
    sa.Column('validation_progress', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['captain_id'], ['raid_participant.id'], ),
    sa.ForeignKeyConstraint(['second_id'], ['raid_participant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raid_team_id'), 'raid_team', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raid_team_id'), table_name='raid_team')
    op.drop_table('raid_team')
    op.drop_index(op.f('ix_raid_participant_id'), table_name='raid_participant')
    op.drop_table('raid_participant')
    op.drop_index(op.f('ix_raid_security_file_id'), table_name='raid_security_file')
    op.drop_table('raid_security_file')
    op.drop_index(op.f('ix_raid_document_id'), table_name='raid_document')
    op.drop_table('raid_document')
    # ### end Alembic commands ###
