"""phonebook

Create Date: 2025-06-26 01:04:23.300580
"""

from collections.abc import Sequence
from typing import TYPE_CHECKING

from app.core.groups.groups_type import GroupType

if TYPE_CHECKING:
    from pytest_alembic import MigrationContext

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "abcde3aa7341"
down_revision: str | None = "9fc3dc926600"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "phonebook_association_groupement",
        sa.Column("manager_group_id", sa.String(), nullable=True),
    )
    op.create_foreign_key(
        "fk_phonebook_association_groupement_manager_group_id_core_group",
        "phonebook_association_groupement",
        "core_group",
        ["manager_group_id"],
        ["id"],
    )
    conn = op.get_bind()
    admin_group = conn.execute(
        sa.text(
            """SELECT id FROM core_group
        WHERE name = :group_name
        """,
        ).bindparams(group_name=GroupType.admin.value),
    ).fetchone()
    if not admin_group:
        conn.execute(
            sa.text(
                """INSERT INTO core_group (id, name) VALUES (:group_id, :group_name)""",
            ).bindparams(
                group_id=GroupType.admin.value,
                group_name="Admin",
            ),
        )
    conn.execute(
        sa.text(
            """UPDATE phonebook_association_groupement
        SET manager_group_id = :group_id
        """,
        ).bindparams(group_id=GroupType.admin.value),
    )
    op.alter_column(
        "phonebook_association_groupement",
        "manager_group_id",
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_phonebook_association_groupement_manager_group_id_core_group",
        "phonebook_association_groupement",
        type_="foreignkey",
    )
    op.drop_column("phonebook_association_groupement", "manager_group_id")
    # ### end Alembic commands ###


def pre_test_upgrade(
    alembic_runner: "MigrationContext",
    alembic_connection: sa.Connection,
) -> None:
    # Create the association table with the new groupement_id column
    pass


def test_upgrade(
    alembic_runner: "MigrationContext",
    alembic_connection: sa.Connection,
) -> None:
    # Check that the groupement table has been created and populated
    pass
