"""adding-invite-token

Revision ID: ff5899b42625
Revises: 91b29f00c75d
Create Date: 2024-03-30 11:49:01.328962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff5899b42625'
down_revision: Union[str, None] = '91b29f00c75d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raid_invite',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['raid_team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raid_invite_id'), 'raid_invite', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raid_invite_id'), table_name='raid_invite')
    op.drop_table('raid_invite')
    # ### end Alembic commands ###
